name       : tuxpaint
version    : 0.9.23
release    : 4
source     :
    - http://kent.dl.sourceforge.net/project/tuxpaint/tuxpaint/0.9.23/tuxpaint-0.9.23.tar.gz : 349919c44e0fa252581be6e3242251fb62d20a82c971e99be96d648462bf6926
license    : GPL-2.0-or-later
component  : games.learning
summary    : Drawing program designed for young children
description: |
    Drawing program designed for young children
builddeps  :
    - pkgconfig(fribidi)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_Pango)
    - pkgconfig(SDL_ttf)
    - gperf
    - libpaper-devel
setup      : |
    sed -i 's|kbuildsycoca4||' Makefile
    %make clean
    make -j1 translations
build      : |
    %make PREFIX=/usr
install    : |
    make -j1 \
      DESTDIR="$installdir" \
      PREFIX=/usr \
      GNOME_PREFIX=/usr \
      X11_ICON_PREFIX="$installdir/usr/share/pixmaps" \
      install

    install -D -d -m 00755 $installdir/usr/share/bash-completion/completions
    mv $installdir/etc/bash_completion.d/tuxpaint-completion.bash \
      $installdir/usr/share/bash-completion/completions/tuxpaint
    rm -r $installdir/etc/bash_completion.d
