name       : tuxpaint
version    : 0.9.22
release    : 3
source     :
    - http://kent.dl.sourceforge.net/project/tuxpaint/tuxpaint/0.9.22/tuxpaint-0.9.22.tar.gz : 8abd932f8e36fad795bba0290c094c9c221e424c4b9aa8c763b7fb3459cb2be3
license    : GPL-2.0-or-later
component  : games.learning
summary    : Drawing program designed for young children
description: |
    Drawing program designed for young children
builddeps  :
    - pkgconfig(fribidi)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_Pango)
    - pkgconfig(SDL_ttf)
    - gperf
    - libpaper-devel
setup      : |
    %make clean
    make -j1 translations
build      : |
    %make PREFIX=/usr
install    : |
    make -j1 \
      DESTDIR="$installdir" \
      PREFIX=/usr \
      GNOME_PREFIX=/usr \
      X11_ICON_PREFIX="$installdir/usr/share/pixmaps" \
      install

    install -D -d -m 00755 $installdir/usr/share/bash-completion/completions
    mv $installdir/etc/bash_completion.d/tuxpaint-completion.bash \
      $installdir/usr/share/bash-completion/completions/tuxpaint
    rm -r $installdir/etc/bash_completion.d
